// thread 'main' panicked at src\middleend\type_checker.rs:1592:17:
// internal error: entered unreachable code
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
// 

extern eoan(izpzucf: bool, crv: f32, pmtovet: bool, reuhili: Gmrxvns) -> u64;
func htzck(kfdokaax: Qzkxaokhpm, zbzr: u32, bgmvav: Pkxoy) -> u64 {
    let uq: Wubiy = emlfrtfp(-true, 14, 25, skopl);
    continue;
    return ahiib(-74, tl, -2).vq;
    while (true) {
        continue;
        while (uq.xcxuxmnc) {
}
}
}
func k(jsfkvwlz: L, yrzc: Iecccbboq, wkyluglvo: u32, xdkco: Josth, gu: Mymg) -> Jmnkqi {
    false.iozxlii;
    let fhuxr: bool = mddxovtamn();
    return rm();
}
func ezhzmik(ujey: Gv) -> Vzojulwfvj {
}
func lnbhlwmokw(u: u32, hvsybik: Iuebyxf) -> i32 {
    true;
}

func main() -> u32 { return 0; }
